### ISSUE TITLE
Implement basic game functionality

### ISSUE THREAD

**Issue by j-germino** [wustlcse237sp20/project-blackjack_237project#3]
Hit and Stand methods in the Player class need to be completed for the UI to function correctly. Additionally a method in the player class is needed that would automatically play that player's hand according to the rules for hitting/standing as a dealer.

**Comment by j-germino** [comment]
Also, the shuffleDeck and dealOutHands methods in the Deck class (not sure if this is the best place for them) need to be completed for the basic UI to work

**Comment by bnd25** [comment]
Most basic methods are done.
